### ISSUE TITLE
ITP default values differ from Tuning Parameters

### ISSUE THREAD

**Issue by judober** [SciML/SimpleNonlinearSolve.jl#108]
First of all, thank you for this great package!

When looking through the documentation of the `ITP`-Method (and the code), I noticed that the default values of the parameters are different between the header (==code) and the 'Tuning Parameters' section which seems to be wrong.
Is there a reason that k2 is not an int as recommended in the text?

**Comment by ChrisRackauckas** [comment]
I think the docstrings and such just didn't get updated. On the int thing, maybe @DaniGlez can chime in

**Comment by DaniGlez** [comment]
This did indeed pop up in the discussion we had with Oscar, I think we just did not act on this specific point (probably because I was not sure if the default values were coming from some analysis I was not aware of): https://github.com/SciML/DiffEqBase.jl/pull/917#issuecomment-1646235996

But it seems indeed sensible to set it to 2, and we can port that to the InternalITP from DiffEqBase as well
